dist: trusty
sudo: required

language: go
go:
  - 1.9.1

go_import_path: github.com/alibaba/pouch

notifications:
  webhooks:
    urls:
      - http://47.96.190.121:6789/ci_notifications
    on_failure: always
    on_error: always

before_install:
  |
    git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md$)' || {
      echo travis doesn\'t run for document-only changed
      exit
    }

    sudo apt-get update -qq
    sudo apt-get install -y -qq autoconf automake

env:
  - TEST_SUITE=unittest
  - TEST_SUITE=integrationtest
  - TEST_SUITE=criv1alpha1test
  - TEST_SUITE=criv1alpha2test

script: |
  if [[ "${TEST_SUITE}" = "unittest" ]]; then
    hack/install/install_ci_related.sh
    make unit-test || travis_terminate 1
    make coverage
  elif [[ "${TEST_SUITE}" = "integrationtest" ]]; then
    make build
    make build-daemon-integration
    TEST_FLAGS= make build-integration-test
    sudo env "PATH=$PATH" make install

    sudo env "PATH=$PATH" make download_dependencies
    sudo env "PATH=$PATH" make integration-test || travis_terminate 1
    make coverage
  elif [[ "${TEST_SUITE}" = "criv1alpha1test" ]]; then
    make build
    TEST_FLAGS= make build-daemon-integration
    sudo env "PATH=$PATH" make install

    sudo env "PATH=$PATH" make download_dependencies
    sudo env "PATH=$PATH" make cri-v1alpha1-test || travis_terminate 1
    make coverage
  else
    make build
    TEST_FLAGS= make build-daemon-integration
    sudo env "PATH=$PATH" make install

    sudo env "PATH=$PATH" make download_dependencies
    sudo env "PATH=$PATH" make cri-v1alpha2-test || travis_terminate 1
    make coverage
  fi

after_success:
- bash <(curl -s https://codecov.io/bash) || echo Codecov_Did_Not_Collect_Coverage_Reports
